USE CX_180_DAY7;

SELECT UPPER('sindhu');

CREATE TABLE EmployeeDATA (
    EmpID INT PRIMARY KEY,
    EmpName VARCHAR(50),
    Salary DECIMAL(10,2),
    Bonus DECIMAL(10,2),
    Department VARCHAR(50),
    NetSalary DECIMAL(10,2)
);


INSERT INTO EmployeeDATA (EmpID, EmpName, Salary, Bonus, Department,NetSalary)
VALUES
(1, 'Amit', 50000, 5000, 'IT',NULL),
(2, 'Sneha', 60000, 7000, 'HR',NULL),
(3, 'Raj', 45000, 4000, 'Finance',NULL),
(4,'KIRAN',50000,5000,'BANKING',55000);

SELECT * FROM EmployeeDATA;

/* SCALAR FUNCTION
Syntax :
CREATE FUNCTION dbo.FunctionName
(
    @value1 INT,
    @value2 INT
)
RETURNS INT
AS
BEGIN
    DECLARE @result INT;
    SET @result = @value1 + @value2;
    RETURN @result;
END;
*/
-- A FUNCTION THAT TAKES 2 INPUTS, ADDS THEM AND RETURNS THE SUM AS OUTPUT
CREATE FUNCTION DBO.SUM_2IPS(@INPUT1 DECIMAL(10,2),@INPUT2 DECIMAL(10,2))
RETURNS DECIMAL(10,2)
AS BEGIN
    DECLARE @RESULT DECIMAL(10,2); -- DECLARING VARIABLE NAME ALONG WITH ITS DATATYPE
    SET @RESULT = @INPUT1 + @INPUT2; -- INITIALIZING VARIABLE WITH INPUT1+INPUT2
    RETURN @RESULT;
END;
-- TO CALL A FUNCTION --> SELECT DBO.FUNCTIONNAME(PARAMETERS);
SELECT DBO.SUM_2IPS(SALARY,BONUS) AS NETSALARY FROM EmployeeDATA;
SELECT * FROM EmployeeDATA;
-- UPDATE THIS INFORMATION IN THE TABLE
UPDATE EmployeeDATA
SET NETSALARY= DBO.SUM_2IPS(SALARY,BONUS);

-- Table-Valued Function
/* Syntax
CREATE FUNCTION dbo.FunctionName (@value INT)
RETURNS TABLE AS RETURN
(
    SELECT *
    FROM table_name
    WHERE column_name > @value
);
*/

-- VIEW HIGH SALARIED EMPLOYEES
CREATE FUNCTION DBO.HIGHINFO_ABOVELIMIT(@AMOUNT DECIMAL(10,2))
RETURNS TABLE AS 
RETURN
(
SELECT * FROM EmployeeDATA WHERE Salary>@AMOUNT
);

-- CALL TABLE VALUED FUNCTION
SELECT * FROM DBO.HIGHINFO_ABOVELIMIT(50000);

-- HIGH BONUS EMPLOYEES
CREATE FUNCTION DBO.HIGHINFO_ABOVELIMIT2(@AMOUNT DECIMAL(10,2))
RETURNS TABLE AS 
RETURN
(
SELECT * FROM EmployeeDATA WHERE BONUS>=@AMOUNT
);

-- CALL TABLE VALUED FUNCTION
SELECT * FROM DBO.HIGHINFO_ABOVELIMIT2(5000);

-- CALCULATE NET SALARY DEPARTMENT WISE 
CREATE FUNCTION DBO.DEPARTWISE_NETSAL(@DEPART VARCHAR(50))
RETURNS TABLE
AS RETURN (SELECT SUM(NETSALARY) AS TOTAL_NET_SALARY FROM EmployeeDATA
WHERE Department=@DEPART);

-- CALL THE FUNCTION AND VIEW THE DATA
SELECT * FROM DBO.DEPARTWISE_NETSAL('HR');