-- GROUPBY AND HAVING CLAUSE
USE cx_180_day4;

-- VIEW CONTENTS OF THE TABLE TIPS
SELECT * FROM TIPS;

SELECT SUM(TOTAL_BILL) AS OVERALLBILL FROM TIPS;

SELECT SUM(TOTAL_BILL) AS OVERALLBILL FROM TIPS WHERE SEX='FEMALE';

-- DISPLAY GENDER WISE OVERALL BILL : USE GROUP BY
SELECT SEX,SUM(TOTAL_BILL) AS OVERALLBILL FROM TIPS GROUP BY SEX;

-- ROUND UP ABOVE OVERALL BILL TO 2 DECIMAL PLACES
SELECT SEX,ROUND(SUM(TOTAL_BILL),2) AS OVERALLBILL FROM TIPS GROUP BY SEX;

-- DISPLAY GENDER AND DAY WISE AVERAGE BILL(ROUND UP AVERAGE BILL TO 1 DECIMAL PLACE)
SELECT SEX,DAY,ROUND(AVG(TOTAL_BILL),1) AS AVGBILL FROM TIPS GROUP BY SEX,DAY;

-- GENDER WISE SMOKER COUNT
SELECT SEX,COUNT(SMOKER) AS TOTAL_SMOKERCOUNT FROM TIPS GROUP BY SEX;

-- GENDER, TIME AND DAY WISE total TIPs. SORT THE DATA IN DESC ORDER OF TOTAL TIPS
SELECT * FROM TIPS;

SELECT SEX,TIME,DAY,SUM(TIP) AS TOTAL_TIPS FROM TIPS GROUP BY SEX,TIME,DAY 
ORDER BY TOTAL_TIPS DESC;

-- SIZE WISE TOTAL BILL ON SUNDAY
SELECT SIZE,ROUND(SUM(TOTAL_BILL),0) AS OVERALLBILL FROM TIPS 
WHERE DAY='SUN' 
GROUP BY SIZE;

-- SIZE WISE TOTAL BILL ON SUNDAY WHERE OVERALLBILL IS GREATER THAN 400
SELECT SIZE,ROUND(SUM(TOTAL_BILL),0) AS OVERLLBILL FROM TIPS 
WHERE DAY ='SUN'
GROUP BY SIZE
HAVING SUM(TOTAL_BILL)>400;

-- GENDER WISE TOTAL TIP ON THURSDAY WHERE TOTAL TIP IS MORE THAN 85
SELECT SEX,SUM(TIP) AS TOTALTIP FROM TIPS
WHERE DAY='THUR'
GROUP BY SEX
HAVING SUM(TIP)>85;

/* SUBQUERIES

1.Single Row Subquery
Returns only one row and is used with operators like =, <, >, <=, >=, <>.
 Syntax:
SELECT column1
FROM table1
WHERE column2 = (SELECT column2 FROM table2 WHERE condition);
*/
-- THE DAY WHICH FETCHED THE HIGHEST TIP 
SELECT * FROM TIPS ORDER BY TIP DESC;

SELECT DAY FROM TIPS WHERE TIP = 10;

SELECT MAX(TIP) FROM TIPS;

SELECT DAY FROM TIPS WHERE TIP = (SELECT MAX(TIP) FROM TIPS);
SELECT DAY,TIP FROM TIPS WHERE TIP = (SELECT MAX(TIP) FROM TIPS);

-- DISPLAY RECORD WITH HIGHEST TOTALBILL
SELECT * FROM TIPS WHERE TOTAL_BILL = (SELECT MAX(TOTAL_BILL) FROM TIPS);


/*
2. Multi Row Subquery
Returns more than one row for one column, and is used with operators like IN, ANY, ALL.

A. Using IN
DISPLAY CUSTOMER DETAILS OF ONLY THOSE CUSTOMERS WHO HAVE GIVEN TIPS MORE THAN 5
*/
SELECT TIP FROM TIPS WHERE TIP>5;

SELECT SEX,SMOKER,DAY,TIME FROM TIPS WHERE TIP IN (SELECT TIP FROM TIPS WHERE TIP>5);
-- SELECT SEX,SMOKER,DAY,TIME FROM TIPS WHERE TIP IN (5.6,5.7,5.9,6,6.2,7,......)

/* B. Using ANY
Display customers whose tip is greater than ANY tip given on Thursday.
*/
SELECT * FROM TIPS WHERE TIP > ANY(SELECT TIP FROM TIPS WHERE DAY='THUR');
-- EXAMPLE: COMPARING ALL TIPS BEING FETCHED (1.3,4.5,10) WITH THURSDAY TIPS - 1,2,3,4
-- ANY ? ANY WILL COMPARE 1.3 WITH 1,2,3,4 : IT WILL CHECK IS 1.3>1 OR 1.3>3 OR 1.3>3 OR 1.3>4 = DISPLAY THE RECORD IF ANY ONE SATISFIES
-- 4.5 > 1, 4.5>2,4.5>3...DISPLAY 4.5 RECORD
-- 10>1,10>2,10>3 .... DISPLAY 10 RECORD

/*  C. Using ALL
Display customers whose tip is greater than ALL tips given on Thursday.
*/
SELECT * FROM TIPS WHERE TIP > ALL(SELECT TIP FROM TIPS WHERE DAY='THUR');
-- EXAMPLE : COMPARING ALL TIPS BEING FETCHED (1.3,4.5,10) WITH THURSDAY TIPS - 1,2,3,4
-- ALL? ALL WILL COMPARE 1.3 WITH 1,2,3,4: IT WILL ONLY FETCH IF 1.3 IS GREATER THAN ALL 1,2,3,4: 1.3 WILL NOT BE FETCHED
-- 4.5 >1 AND 4.5>2 AND 4.5>3 AND 4.5>4 = TRUE : FETCH 4.5 RECORD
-- 10>1 AND 10>2 AND 10>3 AND 10>4 : TRUE : FETCH 10 RECORD

/* JOINS 
CREATE BELOW TABLES WITH RESPECTIVE CONTENT 
*/

CREATE TABLE DEPARTMENTS
(DEPTID INT,
DEPTNAME VARCHAR(MAX));


CREATE TABLE EMPLOYEES
(
EMPID INT,
EMPNAME VARCHAR(MAX),
SALARY DECIMAL(15,2),
DOJ DATE,
DEPARTMENTTID INT);

INSERT INTO DEPARTMENTS
VALUES (101,'SALES'),
(102,'HR'),
(103,'FINANCE');

INSERT INTO EMPLOYEES VALUES (1,'AKASH',85000,'20200513',101),
(2,'PRIYA',98500,'20250715',123),
(3,'LOKESH',99999,'20220221',102),
(4,'SANIF',895678,'20230808',101);

SELECT * FROM DEPARTMENTS;

SELECT * FROM EMPLOYEES;

/*
INNER JOIN SYNTAX: 
Select * from table1
Inner join Table2
On table1.colname = table2.colname
*/
SELECT * FROM EMPLOYEES AS EMP -- LEFT TABLE
INNER JOIN DEPARTMENTS AS DEPT -- RIGHT TABLE
ON EMP.DEPARTMENTTID = DEPT.DEPTID;

-- DISPLAY ONLY EMPID,EMPNAME,DEPTNAME
SELECT EMP.EMPID,EMP.EMPNAME,DEPT.DEPTNAME FROM EMPLOYEES AS EMP -- LEFT TABLE
INNER JOIN DEPARTMENTS AS DEPT -- RIGHT TABLE
ON EMP.DEPARTMENTTID = DEPT.DEPTID;  

/*
LEFT JOIN. DISPLAY ALL THE RECORDS OF EMPLOYEE TABLE WITH CORRESPONDING DEPARTMENT NAME
SELECT * FROM TABLE1
LEFT JOIN TABLE2
ON TABLE1.COLUMN=TABLE2.COLUMN
*/
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT * FROM EMPLOYEES AS EMP
LEFT JOIN DEPARTMENTS AS DEPT
ON EMP.DEPARTMENTTID = DEPT.DEPTID;

-- DISPLAY ONLY EMPID,EMPNAME,DEPTNAME,DEPTID
-- TRY THIS ONE LATER

-- CTE - TEMPORARY TABLES
-- DISPLAY ONLY THE EMPLOYEE DATA WHERE DEPARTMENT NAME IS NOT YET ALLOCATED

SELECT EMP.EMPNAME,EMP.SALARY,DEPT.DEPTNAME FROM EMPLOYEES AS EMP
LEFT JOIN DEPARTMENTS AS DEPT
ON EMP.DEPARTMENTTID = DEPT.DEPTID;

-- FILTER OUT THE ABOVE DATA WHERE DEPTNAME IS NULL
WITH CTE AS (SELECT EMP.EMPNAME,EMP.SALARY,DEPT.DEPTNAME FROM EMPLOYEES AS EMP
LEFT JOIN DEPARTMENTS AS DEPT
ON EMP.DEPARTMENTTID = DEPT.DEPTID)
SELECT * FROM CTE WHERE DEPTNAME IS NULL;

SELECT * FROM CTE; -- WILL THROW AN ERROR .. WHICH IS A VALID ERROR
-- CTE CANNOT BE ACCESSED INDIVIDUALS. CTES ARE TEMPORARY TABLES,ONLY EXIST UNTIL THAT QUERY EXECUTION.

/*
RIGHT JOIN: SHOW ALL THE DEPARTMENT DETAILS THAT EXIST IN THE COMPANY
*/

-- IN WHICH DEPARTMENT IS HIRING YET TO HAPPEN? USE CTE
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES AS EMP
RIGHT JOIN DEPARTMENTS AS DEPT
ON EMP.DEPARTMENTTID = DEPT.DEPTID;

-- CTE- TEMPORARY TABLES - COMMON TABLE EXPRESSIONS
WITH CTE AS (
SELECT * FROM EMPLOYEES AS EMP
RIGHT JOIN DEPARTMENTS AS DEPT
ON EMP.DEPARTMENTTID = DEPT.DEPTID)
SELECT DEPTNAME FROM CTE WHERE DEPARTMENTTID IS NULL;

/*
FULL JOIN : RETURNS BOTH THE TABLE INFORMATION(LEFT AND RIGHT)
*/
SELECT * FROM EMPLOYEES AS EMP
FULL OUTER JOIN DEPARTMENTS AS DEPT
ON EMP.DEPARTMENTTID = DEPT.DEPTID;


-- CROSS JOIN: RETURNS EVERY POSSIBLE COMBINATION FROM BOTH THE TABLES
-- RETURNS M*N ROWS OF DATA
SELECT * FROM EMPLOYEES
CROSS JOIN DEPARTMENTS ;

-- SELF JOIN  - JOIN WITH ITSELF
ALTER TABLE EMPLOYEES
ADD MANAGERID INT;

SELECT * FROM EMPLOYEES;

UPDATE EMPLOYEES
SET MANAGERID= 3
WHERE EMPID=1 OR EMPID=2;

-- ADD SANIF AS A MANAGER FOR LOKESH

UPDATE EMPLOYEES
SET MANAGERID= 4
WHERE EMPID=3;

SELECT * FROM EMPLOYEES;
/*
SELECT E1.EMPNAME AS MANAGER_NAME,E2.EMPNAME AS EMPOYEE_NAME FROM EMPLOYEES AS E1
JOIN EMPLOYEES AS E2
ON
E1.EMPID=E2.MANAGERID;
*/
SELECT E1.EMPNAME AS MANAGER_NAME,E2.EMPNAME FROM EMPLOYEES AS E1
JOIN EMPLOYEES AS E2
ON E1.EMPID = E2.MANAGERID;


-- UNION
CREATE TABLE TABLE1
(ID INT);

CREATE TABLE TABLE2
(VAL INT);

INSERT INTO TABLE1 VALUES (1),(2),(4),(8);

INSERT INTO TABLE2 VALUES (2),(9),(10),(11),(12);

SELECT * FROM TABLE1;
SELECT * FROM TABLE2;
-- UNION RETURNS UNIQUE SET OF VALUES FROM COMIBNED TABLES
SELECT * FROM TABLE1
UNION -- UNIQUE COMBINATION OF VALUES FROM TABLE1 AND TABLE2
SELECT * FROM TABLE2;

-- UNION ALL RETURNS ALL THE VALUES FROM COMBINED TABLES
SELECT * FROM TABLE1
UNION ALL 
SELECT * FROM TABLE2;