-- GROUPBY AND HAVING CLAUSE
USE cx_180_day4;

-- VIEW CONTENTS OF THE TABLE TIPS
SELECT * FROM TIPS;

-- DISPLAY GENDER WISE OVERALL BILL : USE GROUPBY


-- ROUND UP ABOVE OVERALL BILL TO 2 DECIMAL PLACES


-- DISPLAY GENDER AND DAY WISE AVERAGE BILL(ROUND UP AVERAGE BILL TO 1 DECIMAL PLACE)


-- GENDER WISE SMOKER COUNT


-- GENDER, TIME AND DAY WISE total TIPs. SORT THE DATA IN DESC ORDER OF OVERALL BILL


-- SIZE WISE TOTAL BILL ON SUNDAY


-- SIZE WISE TOTAL BILL ON SUNDAY WHERE OVERALLBILL IS GREATER THAN 400

-- GENDER WISE TOTAL TIP ON THURSDAY WHERE TOTAL TIP IS MORE THAN 85


/* SUBQUERIES

1.Single Row Subquery
Returns only one row and is used with operators like =, <, >, <=, >=, <>.
 Syntax:
SELECT column1
FROM table1
WHERE column2 = (SELECT column2 FROM table2 WHERE condition);
*/
-- THE DAY WHICH FETCHED THE HIGHEST TIP 


-- DISPLAY RECORD WITH HIGHEST TOTALBILL


/*
2. Multi Row Subquery
Returns more than one row for one column, and is used with operators like IN, ANY, ALL.

A. Using IN
DISPLAY CUSTOMER DETAILS OF ONLY THOSE CUSTOMERS WHO HAVE GIVEN TIPS MORE THAN 5
*/


/* B. Using ANY
Display customers whose tip is greater than ANY tip given on Thursday.
*/


/*  C. Using ALL
Display customers whose tip is greater than ALL tips given on Thursday.
*/


/* JOINS 
CREATE BELOW TABLES WITH RESPECTIVE CONTENT 
*/

CREATE TABLE DEPARTMENTS
(DEPTID INT,
DEPTNAME VARCHAR(MAX));


CREATE TABLE EMPLOYEES
(
EMPID INT,
EMPNAME VARCHAR(MAX),
SALARY DECIMAL(15,2),
DOJ DATE,
DEPARTMENTTID INT);

INSERT INTO DEPARTMENTS
VALUES (101,'SALES'),
(102,'HR'),
(103,'FINANCE');

INSERT INTO EMPLOYEES VALUES (1,'AKASH',85000,'20200513',101),
(2,'PRIYA',98500,'20250715',123),
(3,'LOKESH',99999,'20220221',102),
(4,'SANIF',895678,'20230808',101);

SELECT * FROM DEPARTMENTS;

SELECT * FROM EMPLOYEES;

/*
INNER JOIN SYNTAX: 
Select * from table1
Inner join Table2
On table1.colname = table2.colname
*/


-- DISPLAY ONLY EMPID,EMPNAME,DEPTNAME


/*
LEFT JOIN. DISPLAY ALL THE RECORDS OF EMPLOYEE TABLE WITH CORRESPONDING DEPARTMENT NAME
SELECT * FROM TABLE1
LEFT JOIN TABLE2
ON TABLE1.COLUMN=TABLE2.COLUMN
*/


-- DISPLAY ONLY EMPID,EMPNAME,DEPTNAME,DEPTID


-- CTE - TEMPORARY TABLES
-- DISPLAY ONLY THE EMPLOYEE DATA WHERE DEPARTMENT NAME IS NOT YET ALLOCATED





-- CTE CANNOT BE ACCESSED INDIVIDUALS. CTES ARE TEMPORARY TABLES,ONLY EXIST UNTIL THAT QUERY EXECUTION.

/*
RIGHT JOIN: SHOW ALL THE DEPARTMENT DETAILS THAT EXIST IN THE COMPANY
*/


-- IN WHICH DEPARTMENT IS HIRING YET TO HAPPEN? USE CTE



/*
FULL JOIN : RETURNS BOTH THE TABLE INFORMATION(LEFT AND RIGHT)
*/



-- CROSS JOIN: RETURNS EVERY POSSIBLE COMBINATION FROM BOTH THE TABLES
-- RETURNS M*N ROWS OF DATA


-- SELF JOIN  - JOIN WITH ITSELF
ALTER TABLE EMPLOYEES
ADD MANAGERID INT;

SELECT * FROM EMPLOYEES;

UPDATE EMPLOYEES
SET MANAGERID= 3
WHERE EMPID=1 OR EMPID=2;

-- ADD SANIF AS A MANAGER FOR LOKESH

UPDATE EMPLOYEES
SET MANAGERID= 4
WHERE EMPID=3;

SELECT * FROM EMPLOYEES;
/*
SELECT E1.EMPNAME AS MANAGER_NAME,E2.EMPNAME AS EMPOYEE_NAME FROM EMPLOYEES AS E1
JOIN EMPLOYEES AS E2
ON
E1.EMPID=E2.MANAGERID;
*/



-- UNION
CREATE TABLE TABLE1
(ID INT);

CREATE TABLE TABLE2
(VAL INT);

INSERT INTO TABLE1 VALUES (1),(2),(4),(8);

INSERT INTO TABLE2 VALUES (2),(9),(10),(11),(12);

SELECT * FROM TABLE1;
SELECT * FROM TABLE2;
-- UNION RETURNS UNIQUE SET OF VALUES FROM COMIBNED TABLES


-- UNION ALL RETURNS ALL THE VALUES FROM COMBINED TABLES
